### ISSUE TITLE
Raspberrypi unable to get audio

### ISSUE THREAD

**Issue by xiongfeigood** [pion/mediadevices#411]
### Your environment.
  - Version: Raspbian 32bit
  - Browser: *include version*
  - Other Information - *stacktraces, related issues, suggestions how to fix, links for us to have context*

### What did you do?
Raspberry PI 32-bit, libopus-dev installed, but still can't get sound。
Hello, I use webrTC example, if open audio, still cannot establish connection. If I comment Audio out, I can make a connection like this:
```go
s, err := mediadevices.GetUserMedia(mediadevices.MediaStreamConstraints{
 Video: func(c *mediadevices.MediaTrackConstraints) {
  c.FrameFormat = prop.FrameFormatOneOf{frame.FormatI420, frame.FormatYUY2}
  c.Width = prop.Int(640)
  c.Height = prop.Int(480)
 },
  //Audio: func(c *mediadevices.MediaTrackConstraints) {
 / /},
 Codec: codecSelector,
})
```
But if I comment out the Audio item, I can't get the Audio. Is there something wrong with me?

### What did you expect?
I can get sound in chromium. I hope I can get sound through opus，please help me 
### What happened?
```
=============== Constraints ==============

DeviceID: any
VideoConstraints:
  Width: 640 (ideal)
  Height: 480 (ideal)
  FrameRate: any
  FrameFormat: I420,YUY2 (one of values)
AudioConstraints:
  ChannelCount: any
  Latency: any
  SampleRate: any
  SampleSize: any
  IsBigEndian: any
  IsFloat: any
  IsInterleaved: any

================ Best Fit ================

DeviceID: fd0552e9-7f4a-4fa4-9a19-2d7422362b9f
Video:
  Width: 640
  Height: 480
  FrameRate: 0
  FrameFormat: YUY2
Audio:
  ChannelCount: 0
  Latency: 0s
  SampleRate: 0
  SampleSize: 0
  IsBigEndian: false
  IsFloat: false
  IsInterleaved: false
mediadevices/driver/microphone DEBUG: 16:20:35.133973 microphone.go:165: Querying properties
mediadevices/driver/microphone DEBUG: 16:20:35.134122 microphone.go:165: Querying properties
mediadevices DEBUG: 16:20:35.134492 mediadevices.go:156: 
============ Found Properties ============

DeviceID: 39c76093-c9fb-4b21-a5c1-0463af37468a
Video:
  Width: 0
  Height: 0
  FrameRate: 0
  FrameFormat: 
Audio:
  ChannelCount: 2
  Latency: 20ms
  SampleRate: 48000
  SampleSize: 2
  IsBigEndian: false
  IsFloat: false
  IsInterleaved: true

DeviceID: 23915681-2bf8-4028-9b38-48452c7c12b0
Video:
  Width: 0
  Height: 0
  FrameRate: 0
  FrameFormat: 
Audio:
  ChannelCount: 1
  Latency: 20ms
  SampleRate: 48000
  SampleSize: 2
  IsBigEndian: false
  IsFloat: false
  IsInterleaved: true

=============== Constraints ==============

DeviceID: any
VideoConstraints:
  Width: any
  Height: any
  FrameRate: any
  FrameFormat: any
AudioConstraints:
  ChannelCount: any
  Latency: any
  SampleRate: any
  SampleSize: any
  IsBigEndian: any
  IsFloat: any
  IsInterleaved: any

================ Best Fit ================

DeviceID: 23915681-2bf8-4028-9b38-48452c7c12b0
Video:
  Width: 0
  Height: 0
  FrameRate: 0
  FrameFormat: 
Audio:
  ChannelCount: 1
  Latency: 20ms
  SampleRate: 48000
  SampleSize: 2
  IsBigEndian: false
  IsFloat: false
  IsInterleaved: true
pc INFO: 2022/07/10 16:20:35 signaling state changed to have-local-offer
ice WARNING: 2022/07/10 16:20:35 failed to resolve stun host: stun.l.google.com:19302: lookup stun.l.google.com on 183.221.253.100:53: no such host
pc INFO: 2022/07/10 16:20:35 signaling state changed to stable
mediadevices DEBUG: 16:20:35.217695 track.go:167: trying to build video/VP8 rtp reader
```
